Algoritmo "combinações com para "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome Ewerton
// Data atual  : 15/11/2023
Var
n1:inteiro
n2:inteiro


Inicio
para n1 := 1 ate 15 faca
   para n2:=1 ate 15 faca
    escreval (n1+n2)
   fimpara
fimpara

Fimalgoritmo