Algoritmo "combinações "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome ewerton
// Data atual  : 15/11/2023
Var
c1:inteiro
c2:inteiro



Inicio
para c1 := 1 ate 3 faca
   para c2 := 1 ate 3 faca
    escreval (c1,c2)
   fimpara
fimpara
Fimalgoritmo