Algoritmo "em que ano você nasceu"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome Ewerton
// Data atual  : 09/11/2023
Var
ANOATUAL:INTEIRO
ANO:INTEIRO
IDADE : INTEIRO
Inicio
ANOATUAL<-(2023)
ESCREVAL("Em que ano você nasceu?")
leia(ANO)
IDADE <-(ANOATUAL-ANO)
ESCREVAL("Você têm = ",IDADE," ANOS")


Fimalgoritmo