Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/01/2024
Var
F,R: INTEIRO

VAR
INICIO
R<-1
C ,R: INTEIRO
PARA C <- 1 ATE FIB FACA
 R <- R * C
FIMPARA
FIMFUNCAO



Inicio
ESCREVAL ("DIGITE UM NÚMERO ")
LEIA (F)

Fimalgoritmo