Algoritmo "  FUNÇAO FATORIAL "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome Ewerton
// Data atual  : 22/11/2023
Var
z,res: inteiro
funcao fatorial (n: inteiro ): inteiro
var r , c : inteiro
Inicio

r <-1
para c <- 1 até n faca
r <- r * c
fimpara
retorne (r)
fimfuncao
inicio
leia (z)
res <-fatorial (z)
escreval (res)


Fimalgoritmo