Algoritmo "OPERADORES LÓGICOS "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome Ewerton
// Data atual  : 09/11/2023
Var
A, B, C : Inteiro


Inicio

A<-20,B<-30,C<-60
ESCREVAL((A=B) E (B*2=C))
ESCREVAL((A=B) OU (B*2=C))
ESCREVAL(NAO(A=B) E (B*2=C))

Fimalgoritmo