Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome EWERTON
// Data atual  : 03/01/2024
Var
C: INTEIRO
N:INTEIRO
SOMA: INTEIRO

Inicio
N<-0
SOMA<-0
C<-0
PARA C <-1 ATE 4 FACA
ESCREVAL ("DIGITE UM VALOR = ")
LEIA (N)
SOMA <-SOMA + N
C<-C+1
FIMPARA
ESCREVAL (" O VALOR DA SOMA FOI = ",SOMA)

Fimalgoritmo