Algoritmo "quantos dolares você tem?"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome Ewerton
// Data atual  : 09/11/2023
Var
reais, dolares:real


Inicio
Escreval ("quantos reais  você tem?")
leia (reais)
dolares<-(reais /5.5)
Escreval (" isso equivale a = ",dolares)



Fimalgoritmo