Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome EWRTON
// Data atual  : 03/01/2024
Var
SOMA: INTEIRO
N,C:INTEIRO


Inicio
SOMA<-0
C<-1
ESCREVAL ("FUNÇÃO REPITA ")
ESCREVAL ("              ")
REPITA
C<-C+1
ESCREVAL ("DIGITE UM NÚMERO ")
LEIA (N)
SOMA <- SOMA + N
ATE (C>10)
ESCREVAL ("ACUMULOU = ", SOMA)

Fimalgoritmo