Algoritmo "soma dois números FUNÇÃO  "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : EWERTON
// Data atual  : 20/11/2023
Var
N1:INTEIRO
N2:INTEIRO
PROCEDIMENTO SOMA (A,B:INTEIRO )
Inicio
A<-10
B<-10
ESCREVAL ("A SOMA DE A + B = ", A+B)
FIMPROCEDIMENTO
INICIO
N1<-10
N2<-10
SOMA (N1,N2)

Fimalgoritmo