Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome EWERTON
// Data atual  : 02/01/2024
Var
C, N,RESULT: INTEIRO


Inicio
ESCREVAL ("CONTADOR REPITA ")
C<-0

LEIA (N)
REPITA

C<-C+1
RESULT<- C*N
ESCREVAL (C," X ",N," = ",RESULT)
ATE (C>=10)


Fimalgoritmo