Algoritmo "utilizando funções"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : EWERTON
// Data atual  : 21/11/2023
Var
N1:INTEIRO
N2:INTEIRO
S:INTEIRO
FUNCAO SOMA (A,B:INTEIRO ):INTEIRO
INICIO

RETORNE  A+B


FIMFUNCAO
Inicio
N1<-10
N2<-10
S<-SOMA(N1,N2)
ESCREVA(S)

Fimalgoritmo