Algoritmo "VETOR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ewerton
// Data atual  : 24/11/2023
Var
C:INTEIRO
V: VETOR [1..10] DE INTEIRO

Inicio
PARA C <- 1 ATE 10 FACA
ESCREVAL ("DIGITE O VALOR GUARDADO NO VETOR ")
LEIA (V[C])
FIMPARA
PARA C <- 1 ATE 10 FACA
ESCREVAL ("POSIÇÃO ",C,"° =>",V[C])
FIMPARA

Fimalgoritmo