Algoritmo "vetores "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : EWERTON
// Data atual  : 24/11/2023
Var
C: INTEIRO
V: VETOR [1..6] DE INTEIRO
Inicio

PARA C <- 1 ATE 6 FACA
ESCREVAL ("DIGITE O PRIMEIRO" ,C,  "°VALOR : ")
LEIA (V[C])
FIMPARA
PARA C <-1 ATE 6 FACA
ESCREVAL (C,"°= [",V[C] ,"]")
FIMPARA
Fimalgoritmo